# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from genpy/TestPythonSafeSubfields.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy.msg

class TestPythonSafeSubfields(genpy.Message):
  _md5sum = "9786d1584b4cc594d501a4c44214bf1b"
  _type = "genpy/TestPythonSafeSubfields"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """genpy/TestPythonSafe[] def

================================================================================
MSG: genpy/TestPythonSafe
string from
"""
  __slots__ = ['def_']
  _slot_types = ['genpy/TestPythonSafe[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       def_

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TestPythonSafeSubfields, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.def_ is None:
        self.def_ = []
    else:
      self.def_ = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.def_)
      buff.write(_struct_I.pack(length))
      for val1 in self.def_:
        _x = val1.from_
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.def_ is None:
        self.def_ = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.def_ = []
      for i in range(0, length):
        val1 = genpy.msg.TestPythonSafe()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.from_ = str[start:end].decode('utf-8')
        else:
          val1.from_ = str[start:end]
        self.def_.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.def_)
      buff.write(_struct_I.pack(length))
      for val1 in self.def_:
        _x = val1.from_
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.def_ is None:
        self.def_ = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.def_ = []
      for i in range(0, length):
        val1 = genpy.msg.TestPythonSafe()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.from_ = str[start:end].decode('utf-8')
        else:
          val1.from_ = str[start:end]
        self.def_.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
